move display_{error,info}box to share/firstboot
Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/share/firstboot b/share/firstboot
--- a/share/firstboot
+++ b/share/firstboot
@@ -17,6 +17,63 @@
 #
 #   Written by Olaf Kirch <okir@suse.com>
 
+function d_stolen_from_jeos {
+
+	dialog_out=`mktemp -qt 'firstboot-XXXXXX'`
+
+	retval=
+	while true
+	do
+		retval=0
+		dialog --backtitle "$PRETTY_NAME" --output-fd 3 "$@" 3>"${dialog_out}" || retval=$?
+		case $retval in
+		  0)
+			# need || true as dialog doesn't write newlines
+			read result < $dialog_out || true
+			rm -f $dialog_out
+			return 0
+			;;
+		  1)
+			echo "$(xargs -a "$dialog_out")" >/var/log/jeos
+			dialog --backtitle "$PRETTY_NAME" --yesno $"Do you really want to quit?" 0 0 && exit 1
+			continue
+			;;
+		  255)
+			# xargs to remove whitespaces
+			echo "$(xargs -a "$dialog_out")" >/var/log/jeos
+			result_error="$(xargs -a "$dialog_out")"
+			if [ -z "$result_error" ]; then
+				dialog --backtitle "$PRETTY_NAME" --yesno $"Do you really want to quit?" 0 0 && exit 1
+				continue
+			fi
+			logger -p err -t jeos-firstboot "$result_error"
+			dialog --backtitle "$PRETTY_NAME" --msgbox $"Exiting due to error, please check the system log" 0 0
+			rm -f $dialog_out
+			exit 2
+			;;
+		esac
+	done
+}
+
+case $(type d 2>/dev/null)
+"d is a function"*)
+    : ;;
+*)  alias d=d_stolen_from_jeos;;
+esac
+
+##################################################################
+# Display an error box
+##################################################################
+function display_errorbox {
+
+    d --title ERROR --msgbox "$*" 8 60
+}
+
+function display_infobox {
+
+    d --infobox "$*" 5 40
+
+}
 
 ##################################################################
 # request_password MESSAGE
