Getting tpm sealing to work again
Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/firstboot/00fde b/firstboot/00fde
--- a/firstboot/00fde
+++ b/firstboot/00fde
@@ -9,12 +9,55 @@ FDE_SEAL_PCR_LIST=0,2,9
 FDE_SEAL_PCR_LIST=0,2,4
 FDE_SEAL_PCR_BANK=sha256
 
+# It appears that the 128 is the maximum size of what TPM2_Load is willing to handle
+FDE_KEY_SIZE_BYTES=128
+
 FDE_ROOTKEY_EFIVAR_NAME=RootKey
 FDE_ROOTKEY_EFIVAR_FULL=RootKey-58aca851-8af7-4738-a542-266e21f5cad9
 
 # These need to match exactly what grub2 uses to create the SRK
 TPM2_SRK_ATTRS="userwithauth|restricted|decrypt|fixedtpm|fixedparent|noda|sensitivedataorigin"
 
+##################################################################
+# Helper functions for temp file/dir creation
+##################################################################
+function fde_make_tempdir {
+
+    declare -g FDE_TEMP_DIR
+
+    if [ -z "$FDE_TEMP_DIR" ]; then
+	FDE_TEMP_DIR=$(mktemp -d -p /dev/shm fde.XXXXXX)
+    fi
+
+    echo $FDE_TEMP_DIR
+}
+
+function fde_clean_tempdir {
+
+    declare -g FDE_TEMP_DIR
+
+    if [ -n "$FDE_TEMP_DIR" ]; then
+    	rm -rf $FDE_TEMP_DIR
+    	unset FDE_TEMP_DIR
+    fi
+}
+
+function fde_make_tempfile {
+
+    echo "$(fde_make_tempdir)/$1"
+}
+
+##################################################################
+# Display an error box
+##################################################################
+function fde_error {
+
+    d --title ERROR --infobox "$*" 5 40
+}
+
+##################################################################
+# Locate the encrypted root device
+##################################################################
 function __get_root_dev {
 
     df / | grep /dev/ | cut -f1 -d' '
@@ -108,9 +151,17 @@ function request_password {
     return 1
 }
 
+##################################################################
+# Write a passphrase to a file s.th. it can be used as
+# --key-file argument.
+# luksChangeKey requires two of these files, so we pass a string
+# as first argument (eg newpass, oldpass)
+##################################################################
 function luks_write_password {
 
-    filename=$(mktemp -p /dev/shm luks.XXXXXX)
+    filename=$(fde_make_tempfile "$1")
+    shift
+
     echo -n "$*" >$filename
     echo $filename
 }
@@ -121,7 +172,7 @@ function luks_drop_pass {
     old_pass="$2"
 
     d --infobox "Dropping old recovery password" 3 40
-    old_keyfile=$(luks_write_password "${old_pass}")
+    old_keyfile=$(luks_write_password oldpass "${old_pass}")
     if ! cryptsetup luksRemoveKey "${luks_dev}" ${old_keyfile}; then
 	echo "Warning: luksRemoveKey indicates failure" >&2
     fi
@@ -142,8 +193,8 @@ function luks_change_password {
 
     d --infobox "Updating LUKS recovery password" 3 40
 
-    old_keyfile=$(luks_write_password "${luks_old_password}")
-    new_keyfile=$(luks_write_password "${result_password}")
+    old_keyfile=$(luks_write_password oldpass "${luks_old_password}")
+    new_keyfile=$(luks_write_password newpass "${result_password}")
     if ! cryptsetup --key-file "${old_keyfile}" luksChangeKey --pbkdf pbkdf2 "${luks_dev}" ${new_keyfile}; then
 	# FIXME: dialog
 	echo "Warning: luksAddKey indicates failure" >&2
@@ -166,7 +217,7 @@ function luks_add_password {
 
     d --infobox "Updating LUKS recovery password" 3 40
 
-    new_keyfile=$(luks_write_password "${result_password}")
+    new_keyfile=$(luks_write_password newpass "${result_password}")
     if ! cryptsetup --key-file "${luks_keyfile}" luksAddKey --pbkdf pbkdf2 "${luks_dev}" ${new_keyfile}; then
 	echo "Warning: luksAddKey indicates failure" >&2
 	return 1
@@ -181,7 +232,7 @@ function luks_set_random_key {
     luks_keyfile="$2"
 
     new_keyfile=/.tpm2.keyfile
-    dd if=/dev/random bs=1 count=128 of=$new_keyfile
+    dd if=/dev/random bs=1 count=$FDE_KEY_SIZE_BYTES of=$new_keyfile
     cryptsetup --key-file "${luks_keyfile}" luksChangeKey --pbkdf pbkdf2 $luks_dev $new_keyfile
     cp $new_keyfile "${luks_keyfile}"
     rm -f $new_keyfile
@@ -193,24 +244,21 @@ function luks_reencrypt {
     luks_dev="$1"
     luks_keyfile="$2"
 
-    if false; then
-	# whenever kiwi starts to support LUKS2
-	cryptsetup --key-file "${luks_keyfile}" reencrypt $luks_dev
-    else
-	cryptsetup-reencrypt --key-file "${luks_keyfile}" --progress-frequency 1 $luks_dev
-    fi
-}
-
-function tpm2_tempdir {
-
-    mkdir -p /tmp/tpm2
-    echo /tmp/tpm2
+    # Online reencryption works with LUKS2 only. If we ever want to do FDE with luks1,
+    # we need to perform reencryption during installation, after dd'ing the image to
+    # disk and prior to mounting it.
+    {
+	cryptsetup reencrypt --key-file "$luks_keyfile" --progress-frequency 1 $luks_dev 2>&1|
+	    sed -u 's/.* \([0-9]*\)[0-9.]*%.*/\1/'
+	    echo 100
+    } | d --gauge "Reencrypting LUKS device $luks_dev" 7 40
 }
 
 function tpm_build_pcrset {
 
     grub_cfg="$1"
 
+    echo "Building PCR set for $FDE_SEAL_PCR_LIST" >&2
     for index in ${FDE_SEAL_PCR_LIST//,/ }; do
 	case $index in
 	9)
@@ -245,21 +293,20 @@ function tpm_seal_key {
     pubkey=$3
     privkey=$4
 
-    dir=$(tpm2_tempdir)
-
-    context=$dir/primary.ctx
-    session=$dir/session.ctx
-    policy=$dir/policy.tpm
+    context=$(fde_make_tempfile primary.ctx)
+    session=$(fde_make_tempfile session.ctx)
+    policy=$(fde_make_tempfile policy.tpm)
 
     policy_options=$(tpm_policy_options "$pcr_values_file")
 
     tpm2_createprimary --quiet -c $context -a "$TPM2_SRK_ATTRS"
     tpm2_startauthsession --session $session
     tpm2_policypcr --session $session $policy_options --policy $policy
-    tpm2_flushcontext $session
     tpm2_create --quiet -C $context -u $pubkey -r $privkey -L $policy -i $secret
+    retval=$?
+    tpm2_flushcontext $session
 
-    rm -rf $dir
+    return $retval
 }
 
 function tpm_unseal_key {
@@ -269,7 +316,7 @@ function tpm_unseal_key {
     privkey=$3
     unsealed_key_file=$4
 
-    dir=$(tpm2_tempdir)
+    dir=$(fde_make_tempdir)
 
     context=$dir/primary.ctx
     session=$dir/session.ctx
@@ -291,16 +338,23 @@ function tpm_unseal_key {
 
 function seal_key_verify {
 
+    opt_verify=false
+    if [ "$1" == "--verify" ]; then
+	opt_verify=true
+	shift
+    fi
+
     pcr_values_file=$1
     secret=$2
     sealed_key_file=$3
 
-    pubkey=/tmp/sealed-key.pub
-    privkey=/tmp/sealed-key.priv
+    pubkey=$(fde_make_tempfile sealed-key.pub)
+    privkey=$(fde_make_tempfile sealed-key.priv)
 
     if ! tpm_seal_key "$pcr_values_file" $secret $pubkey $privkey; then
-	d --timeout 60 --msgbox "\"Failed to seal disk encryption key to TPM.\"" 5 80
+	# d --timeout 60 --msgbox "\"Failed to seal disk encryption key to TPM.\"" 5 80
 	# Do not exit - hopefully, the user has set a recovery key.
+	return 1
     fi
 
     # The sealed key that grub expects seems to be just
@@ -308,8 +362,8 @@ function seal_key_verify {
     # the private key portion
     cat $pubkey $privkey > $sealed_key_file
 
-    if ! [[ "$FDE_SEAL_PCR_LIST" =~ *[89]* ]]; then
-	unsealed_file=/tmp/unsealed.key
+    if $opt_verify; then
+	unsealed_file=$(fde_make_tempfile unsealed.key)
 	tpm_unseal_key "$pcr_values_file" $pubkey $privkey $unsealed_file
 
 	if ! cmp --quiet $secret $unsealed_file; then
@@ -327,6 +381,24 @@ function seal_key_verify {
 }
 
 
+function tpm_test {
+
+    key_size=$1
+
+    pcr_values_file=$(fde_make_tempfile pcr-values)
+    tpm2_pcrread -o $pcr_values_file $FDE_SEAL_PCR_BANK:$FDE_SEAL_PCR_LIST >&2
+
+    secret=$(fde_make_tempfile secret)
+    dd if=/dev/zero of=$secret bs=$key_size count=1 >&2
+
+    sealed_secret=$(fde_make_tempfile sealed.key)
+    seal_key_verify --verify $pcr_values_file $secret $sealed_secret >&2
+    retval=$?
+
+    fde_clean_tempdir
+    return $retval
+}
+
 function tpm_seal_secret {
 
     secret="$1"
@@ -335,16 +407,18 @@ function tpm_seal_secret {
 
     # using the tpm2-tss FAPI (which pcr-oracle --from-current coes) needs a copy of
     # /etc/tpm2-tss/fapi-config.json 
-    tpm2_pcrread sha256:0,1
+    if false; then
+    tpm2_pcrread sha256:$FDE_SEAL_PCR_LIST
     pcr-oracle --algorithm "$FDE_SEAL_PCR_BANK" \
 		--from-zero 9 \
 		file "${efi_grub_dir}/grub.cfg"
     pcr-oracle --algorithm "$FDE_SEAL_PCR_BANK" \
 		--from-snapshot 0
     pcr-oracle --algorithm "$FDE_SEAL_PCR_BANK" \
-		--from-snapshot 1
+		--from-snapshot 2
     pcr-oracle --algorithm "$FDE_SEAL_PCR_BANK" \
 		--from-current 0
+    fi
 
     # Construct a set of PCR values against which to seal the key.
     # Most of these come straight from the PCR snapshot taken by tpm_record_pcrs
@@ -353,18 +427,13 @@ function tpm_seal_secret {
     # going to be different from the one that got used when booting the installer.
     pcr_values_file=/tmp/pcr-set
     tpm_build_pcrset "${efi_grub_dir}/grub.cfg" >"${pcr_values_file}"
-    od -tx1 $pcr_values_file
-
-    tpm2_pcrread sha256:0,1 -o tmp/values2
-    cmp /tmp/values2 $pcr_values_file
-    pcr_values_file=/dev/null
 
     # Since we're now sealing the key against a predicted value of PCR9 (rather
     # than the actual value), we can no longer verify that the key can be
     # unsealed.
     # FIXME: during initial installation, we should verify that seal/unseal
     # works *at all*.
-    if ! seal_key_verify $pcr_values_file $secret $sealed_secret; then
+    if ! seal_key_verify $pcr_values_file $secret $sealed_secret >&2; then
 	rm -f $sealed_secret
 	# FIXME: this should be an error dialog.
 	# Let's hope the user has set a recovery password
@@ -554,19 +623,46 @@ function fde_setup2 {
     luks_recovery_pass="$3"
 
     if ! [[ "$root_dev" =~ /dev/mapper/.* ]]; then
-	echo "root device does not look like a dm device" >&2
+	fde_error "root device $root_dev does not look like a dm device"
         return 1
     fi
 
     luks_name=$(expr "$root_dev" : ".*/\(.*\)")
     luks_dev=$(luks_get_underlying_device "$luks_name")
+    if [ -z "$luks_dev" ]; then
+        fde_error "Unable to determine underlying LUKS device for $root_dev"
+	return 1
+    fi
+
+    if ! tpm_test $FDE_KEY_SIZE_BYTES 2>/var/log/fde.log; then
+	fde_error "Failed to seal LUKS encryption key."
+	return 1
+    fi
 
     # Change the built-in recovery password to the one provided by the user
     if ! luks_change_password "${luks_dev}" "${luks_recovery_pass}"; then
+	fde_error "Failed to change recovery password."
     	return 1
     fi
 
-    # luks_set_random_key "${luks_dev}" "${luks_keyfile}"
+    luks_reencrypt "${luks_dev}" "${luks_keyfile}"
+
+    luks_set_random_key "${luks_dev}" "${luks_keyfile}"
+
+    efi_grub_dir=/boot/efi/EFI/BOOT
+    tpm_seal_secret "${luks_keyfile}" "${efi_grub_dir}" "$efi_grub_dir/sealed.key"
+}
+
+function foo {
+
+    # it appears that the 128 is the maximum size of what TPM2_Load is willing to handle
+    if ! tpm_test 128 2>/var/log/fde.log; then
+	fde_error "Failed to seal LUKS encryption key."
+	return 1
+    fi
+
+    efi_grub_dir=/boot/efi/EFI/BOOT
+    tpm_seal_secret "/.root.keyfile" "${efi_grub_dir}" "$efi_grub_dir/sealed.key" 2>>/var/log/fde.log
 }
 
 function fde_systemd_firstboot {
@@ -575,7 +671,7 @@ function fde_systemd_firstboot {
 
     # FIXME: rather than hard-coding the recovery password here,
     # have kiwi write it to /.root.something and read it from there
-    fde_setup2 $(__get_root_dev) /.root.keyfile "1234"
+    fde_setup2 $(__get_root_dev) /.root.keyfile "1234" 2>/var/log/fde-firstboot.log
 }
 
 function fde_post {
